var etransfer_language = window.localStorage.getItem("lang");
//etransfer_language: window.localStorage("lang");
var lang = {
    "ENG": {
        "res_lbl_phone": "Tel.:",
        "res_lbl_fax": "Fax:",
        "res_lbl_email": "Email:",
        "res_lbl_web": "Website:",
        "res_lbl_rating": "Rating:",
        "res_cbox_title": "Click to select this partner",
        "res_cbox_text": "Ask For Quotation",
        "res_ncc_badge_alt": "NCC Online Certification",
        "res_smart_badge_alt": "Smart NCC Certification",
        "res_lbl_service_offered": "Service Offered:",
        "res_lbl_lnk_continue": "Continue...",
        "res_ddl_area_code": "Area Code",
        "res_ddl_city_code": "City Code",
        "res_msg_callback_error": "Error was:",
        "res_lbl_callback_approx": "Approx:",
        "res_msg_loading": "Loading ...",
        "res_msg_gmap_geocode": "Geocode was not successful for the following reason:",
        "res_lnk_continue": "Continue...",
        "res_title_ncc_online": "NCC Online Certification",
        "res_title_smart_online": "Smart NCC Certification",
        "res_msg_sending": "Sending...",
        "res_lbl_phone": "Phone:",
        "res_lbl_web": "Website:",
        "res_lbl_email": "Email:",
        "res_lbl_fax": "Fax:",
        "res_alt_phone": "phone",
        "res_alt_web": "website",
        "res_alt_email": "email",
        "res_alt_fax": "fax",
        "res_msg_offer_unable": "Unable to send your offer request. Please try again",
        "res_msg_offer_please": "<h4>Please wait.</h4><p>Be patient, we are processing your request.",
        "res_lbl_paymethod": "Payment Method:",
        "res_lbl_paynote": "Partner Notes:",
        "res_lbl_price": "Price:",
        "res_alt_price": "Price",
        "res_lbl_surname": "Surname:",
        "res_lbl_name": "Name:",
        "res_lbl_companyname": "Company Name:",
        "res_lbl_companycontact": "Contact Name and Surname:",
        "res_booking_msg_sending": "Please select a partner before sending your request...",
        "res_error_sending": "Error sending request, please check all fields and try again...",
        "res_global_select": "Select",
        "res_global_session": "Session Expired",
        "res_global_gohome": "Kindly reload the page or <a href='\home.html'> click here</a> to go to home page",
        "res_offer_accepted": "Offer already assigned to You.",
        "res_offer_refused": "Offer already assigned to another partner.",
        "res_search_msg_pickuparea": "Please select pickup area",
        "res_search_msg_pickupcity": "Please select pickup city",
        "res_search_msg_arrival_area": "Please select destination area",
        "res_search_msg_arrival_city": "Please select destination city",
        "res_search_msg_pickup_time": "Please enter pickup time",
        "res_search_msg_pickup_date": "Please enter pickup date",
        "res_search_msg_vehicletype": "Please select a vehicle type",
        "res_book_msg_name": "Please enter name",
        "res_book_msg_surname": "Please enter surname",
        "res_book_msg_address": "Please enter booking address",
        "res_book_msg_email": "Please enter email",
        "res_book_msg_phone": "Please enter phone",
        "res_book_msg_country": "Please enter country",
        "res_place_offer_msg_price": "Please enter a valid price.",
        "res_home_hiredriver": "Hire Driver",
        "res_home_booknow": "Book Now",
        "res_home_explore_area": "Explore Area",
        "res_home_view_partners": "View Partners",
        "res_home_exit": "Exit",
        "res_search_lbl_head": "Book  <span>Request</span>",
        "res_search_lbl_from": "Pickup Place:",
        "res_search_lbl_to": "Destination:",
        "res_search_lbl_gmap": "Google Map",
        "res_search_lbl_passenger": "N. Passengers:",
        "res_search_lbl_baggage": "N. Baggage:",
        "res_search_lbl_pickupdate": "Pickup Date:",
        "res_search_lbl_pickuptime": "Pickup Time:",
        "res_search_lbl_vehicle": "Vehicle Type:",
        "res_global_btn_send_request": "Hire a driver",
        "res_global_btn_cancel": "Cancel",
        "res_search_result_lbl_head": "Search <span>Results</span>",
        "res_search_result_lbl_select_all": "Select all",
        "res_bookjourney_lbl_head": "Get a <span>Free Quote</span>",
        "res_global_link_enquire_text": "Enquire Selected Partners",
        "res_partner_lbl_mobile": "Mobile:",
        "res_partner_lbl_payment_methods": "Payment methods:",
        "res_partner_lbl_about": "About",
        "res_partner_lbl_available_vehicle": "Avaliable Vehicles",
        "res_partner_lbl_partner": "Address.:",
        "res_partner_lbl_certifications": "Awards:",
        "res_partner_lbl_driver_speaks": "Driver Speaks:",
        "res_areadetails_lbl_allpartners": "All <span>Partners</span>",
        "res_bookjourney_lbl_customer_type": "Is it for Individual or Company?",
        "res_bookjourney_lbl_personnal": "Personal Details",
        "res_global_js_Surname": "Surname:",
        "res_global_lbl_name": "Name:",
        "res_global_lbl_address": "Address:",
        "res_global_lbl_email": "Email:",
        "res_global_lbl_phone": "Phone:",
        "res_global_lbl_zip": "Zip:",
        "res_global_lbl_country": "Country:",
        "res_global_lbl_service_details": "Service Details",
        "res_bookjourney_lbl_selectservice": "Select Service:",
        "res_global_lbl_airporttransfer": "Airport Transfer:",
        "res_bookjourney_lbl_if_airpot_transfer": "If Airport Transfer, Please fill below:",
        "res_global_lbl_air_transfer_type": "Type:",
        "res_bookjourney_ddlitem_arrival": "Arrival:",
        "res_bookjourney_ddlitem_departure": "Departure:",
        "res_global_lbl_flight_number": "Flight No.:",
        "res_booking_lbl_dep_boarding_time": "Departure/Boarding Time:",
        "res_global_lbl_add_info": "Additional Information/Notes:",
        "res_bookjourney_lbl_request_mail": "Your request will be mailed to partners listed below",
        "res_bookjourney_lbl_wait_partners": "Wait for the partners to post their offer and choose wisely. Have a nice journey!",
        "res_global_yes": "Yes",
        "res_global_no": "No",
        "res_bookjourney_radioitem_individual": "Individual",
        "res_bookjourney_radioitem_company": "Company",
        "res_reviewoffer_lbl_offer_head": "<span>Offers Received</span> For your trip",
        "res_reviewoffer_lbl_waiting_head": "<span>Waiting</span> Offer From",
        "res_global_lbl_customer_info": "Customer Info",
        "res_global_lbl_customer_type": "Customer Type:",
        "res_global_lbl_departure_date": "Departure Date:",
        "res_global_lbl_departure_time": "Departure Time:",
        "res_global_lbl_service_type": "Service Type:",
        "res_placeoffer_lbl_main_head": "Place <span>Your Offer</span>",
        "res_placeoffer_lbl_your_offer": "Your Offer",
        "res_placeoffer_btn_text": "Place Offer"
    },
    "ITA": {
        "res_lbl_phone": "Tel.:",
        "res_lbl_fax": "Fax:",
        "res_lbl_email": "Email:",
        "res_lbl_web": "Sito Web:",
        "res_lbl_rating": "Punteggio:",
        "res_cbox_title": "Clicca per seleziononare il partner",
        "res_cbox_text": "Seleziona",
        "res_ncc_badge_alt": "NCC Online Certification",
        "res_smart_badge_alt": "Smart NCC Certification",
        "res_lbl_service_offered": "Servizi offerti:",
        "res_lbl_lnk_continue": "Continua...",
        "res_ddl_area_code": "Provincia",
        "res_ddl_city_code": "Citta",
        "res_msg_callback_error": "Error was:",
        "res_lbl_callback_approx": "Approx:",
        "res_msg_loading": "Caricamento in corso ...",
        "res_msg_gmap_geocode": "Geocode was not successful for the following reason:",
        "res_lnk_continue": "Continua...",
        "res_title_ncc_online": "NCC Online Certification",
        "res_title_smart_online": "Smart NCC Certification",
        "res_msg_sending": "Invio in corso...",
        "res_lbl_phone": "Telefono:",
        "res_lbl_web": "Sito web:",
        "res_lbl_email": "Email:",
        "res_lbl_fax": "Fax:",
        "res_alt_phone": "telefono",
        "res_alt_web": "sito web",
        "res_alt_email": "email",
        "res_alt_fax": "fax",
        "res_msg_offer_unable": "Errore nell\'invio della richiesta. Prova di nuovo...",
        "res_msg_offer_please": "<h4>Attendere...</h4><p>Stiamo processando la richiesta.",
        "res_lbl_paymethod": "Modalità di pagamento:",
        "res_lbl_paynote": "Note:",
        "res_lbl_price": "Prezzo:",
        "res_alt_price": "prezzo",
        "res_lbl_surname": "Cognome:",
        "res_lbl_name": "Nome:",
        "res_lbl_companyname": "Ragione sociale",
        "res_lbl_companycontact": "Contatto, nome e cognome",
        "res_booking_msg_sending": "Selezionare un partner prima di continuare",
        "res_error_sending": "Erroree nell\'invio della richiesta, verifica i campi obbligatori...",
        "res_global_select": "Seleziona",
        "res_global_session": "Sessione scaduta",
        "res_global_gohome": "La sessione è scaduta, <a href=" / ">clicca qui</a> per tornare alla home e riprovare.",
        "res_offer_accepted": "La tua offerta è già stata accettata.",
        "res_offer_refused": "Il servizio è stato assegnato ad un altro vettore.",
        "res_search_msg_pickuparea": "Please select pickup area",
        "res_search_msg_pickupcity": "Please select pickup city",
        "res_search_msg_arrival_area": "Please select destination area",
        "res_search_msg_arrival_city": "Please select destination city",
        "res_search_msg_pickup_time": "Please enter pickup time",
        "res_search_msg_pickup_date": "Please enter pickup date",
        "res_search_msg_vehicletype": "Please select a vehicle type",
        "res_book_msg_name": "Please enter name",
        "res_book_msg_surname": "Please enter surname",
        "res_book_msg_address": "Please enter booking address",
        "res_book_msg_email": "Please enter email",
        "res_book_msg_phone": "Please enter phone",
        "res_book_msg_country": "Please enter country",
        "res_place_offer_msg_price": "Please enter a valid price.",
        "res_home_hiredriver": "Noleggio conducente",
        "res_home_booknow": "Prenota ora",
        "res_home_explore_area": "Esplora Area",
        "res_home_view_partners": "Visualizza Partners",
        "res_home_exit": "uscire",
        "res_search_lbl_head": "Prenota <span>Ora</span>",
        "res_search_lbl_from": "Luogo di pickup:",
        "res_search_lbl_to": "Destinazione:",
        "res_search_lbl_gmap": "Google Map",
        "res_search_lbl_passenger": "N. passeggeri:",
        "res_search_lbl_baggage": "N. di bagagli:",
        "res_search_lbl_pickupdate": "Data di pickup:",
        "res_search_lbl_pickuptime": "Orario di pickup:",
        "res_search_lbl_vehicle": "Tipo di veicolo:",
        "res_global_btn_send_request": "Trova un noleggiantore",
        "res_global_btn_cancel": "Annulla",
        "res_search_result_lbl_head": "Risulati <span>della Ricerca</span>",
        "res_search_result_lbl_select_all": "Seleziona tutto",
        "res_bookjourney_lbl_head": "Richiedi un <span>preventivo gratuito</span>",
        "res_global_link_enquire_text": "Richiedi un preventivo",
        "res_partner_lbl_mobile": "Cellulare:",
        "res_partner_lbl_payment_methods": "Modalita di pagamento:",
        "res_partner_lbl_about": "Informazioni su",
        "res_partner_lbl_available_vehicle": "Veicoli disponibili",
        "res_partner_lbl_partner": "Indirizzo:",
        "res_partner_lbl_certifications": "Certificazioni:",
        "res_partner_lbl_driver_speaks": "Lingue parlate:",
        "res_areadetails_lbl_allpartners": "Tutti i <span>Partner</span>",
        "res_bookjourney_lbl_customer_type": "Privato o azienda?",
        "res_bookjourney_lbl_personnal": "Dati personali",
        "res_global_js_Surname": "Cognome:",
        "res_global_lbl_name": "Nome:",
        "res_global_lbl_address": "Indirizzo:",
        "res_global_lbl_email": "Email:",
        "res_global_lbl_phone": "Telefono:",
        "res_global_lbl_zip": "Cap:",
        "res_global_lbl_country": "Nazione:",
        "res_global_lbl_service_details": "Dettagli del servizio:",
        "res_bookjourney_lbl_selectservice": "Servizio:",
        "res_global_lbl_airporttransfer": "Trasferimento da/per aeroporto:",
        "res_bookjourney_lbl_if_airpot_transfer": "Incaso di transfer aeroportuale comila i seguenti campi:",
        "res_global_lbl_air_transfer_type": "Tipo:",
        "res_bookjourney_ddlitem_arrival": "Arrivo",
        "res_bookjourney_ddlitem_departure": "Partenza",
        "res_global_lbl_flight_number": "Numero del volo:",
        "res_booking_lbl_dep_boarding_time": "Orario di Check in/Atterraggio:",
        "res_global_lbl_add_info": "Informazioni aggiuntive/Note:",
        "res_bookjourney_lbl_request_mail": "Your request will be mailed to partners listed below",
        "res_bookjourney_lbl_wait_partners": "Wait for the partners to post their offer and choose wisely. Have a nice journey!",
        "res_global_yes": "Si",
        "res_global_no":"No",
        "res_bookjourney_radioitem_individual": "Privato",
        "res_bookjourney_radioitem_company": "Azienda",
        "res_reviewoffer_lbl_offer_head": "<span>Offerte ricevute</span> per il tuo viaggio",
        "res_reviewoffer_lbl_waiting_head": "<span>Preventivi</span> richiesti",
        "res_global_lbl_customer_info": "Informazioni sul cliente",
        "res_global_lbl_customer_type": "Tipologia di cliente:",
        "res_global_lbl_departure_date": "Data di partenza:",
        "res_global_lbl_departure_time": "Ora di partenza:",
        "res_global_lbl_service_type": "Tipo di servizio:",
        "res_placeoffer_lbl_main_head": "Invia <span>la tua offerta</span>",
        "res_placeoffer_lbl_your_offer": "La tua offerta",
        "res_placeoffer_btn_text": "Invia l'offerta"

    }
};
